apiVersion: v1
data:
  alertmanager.yml: |
    global: {}
    receivers:
    - name: default-receiver
    - name: slack-notifications
      slack_configs:
      - api_url: '{{ SLACK_API }}'
        channel: '#upcommerce-devs'
        send_resolved: true
        text: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}" 
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: slack-notifications
      repeat_interval: 3h
    templates:
    - /etc/alertmanager/*.tmpl
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: sre
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/version: v0.27.0
    helm.sh/chart: alertmanager-1.10.0
  name: prometheus-alertmanager
  namespace: sre
